apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageUpdateAutomation
metadata:
  name: do-instant-chat
  namespace: flux-system
spec:
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        email: flux-bot@polydo.dev
        name: FluxCD Image Automation
      messageTemplate: "chore(images): update do-instant-chat to {{range .Updated.Images}}{{.NewTag}}{{end}}"
    push:
      branch: main
  update:
    path: ./apps/instant-chat
    strategy: Setters
