apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: messagerie
  namespace: messagerie
spec:
  interval: 1h
  timeout: 5m
  releaseName: messagerie
  chart:
    spec:
      chart: helm/messagerie
      sourceRef:
        kind: GitRepository
        name: messagerie
        namespace: messagerie
      interval: 5m
  values:
    imagePullSecrets:
      - name: gitlab-registry
    image:
      repository: gitlab.polytech.umontpellier.fr:5050/dev-web/messagerie-instantane
      tag: latest # {"$imagepolicy": "messagerie:messagerie"}
      pullPolicy: IfNotPresent
    service:
      type: ClusterIP
      apiPort: 3000
      frontPort: 8081
    env:
      apiPort: 3000
      frontPort: 8081
      frontOrigin: https://messagerie.polydo.dev
      frontOrigins: https://messagerie.polydo.dev
      database:
        host: messagerie-postgresql.messagerie.svc.cluster.local
        user: messagerie_app
        name: instant_mess
      extraEnv:
        - name: COOKIE_SECURE
          value: "true"
        - name: COOKIE_SAMESITE
          value: "None"
        - name: COOKIE_DOMAIN
          value: ".polydo.dev"
    secrets:
      jwtSecret: T9d9MfBplnWBgSnc1zgd-FB_f-zwrnjbT_6tyaLqPvwDUnWcxwS1jvmv9qsM8SM-LfZLfpl2kHTZHHFUSgUpsw
      pepper: Zh6Km-Xdkq1MPwUIt2MVcMqcvv0mtDtdZ4fN77E7gVFHo-vjDY1ypF_ZrT-zyhQzIRHxnAHXnZSqtkDZMAsKLg
      databasePassword: VjKvdXEJ51r4g_jfSgZs9kCHQi0_7q-SmEsy88me8R-2eacl1JSdONfhnzDc9lVZbCRXyeyiyqhfHEN4pX11Ig
    ingress:
      enabled: true
      className: traefik
      annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
      tls:
        - secretName: cloudflare-origin-cert
          hosts:
            - messagerie.polydo.dev
            - api-messagerie.polydo.dev
      frontend:
        host: messagerie.polydo.dev
        path: /
      api:
        host: api-messagerie.polydo.dev
        path: /
