apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: minecraft-server-charts
  namespace: minecraft
spec:
  interval: 1h
  url: https://itzg.github.io/minecraft-server-charts
