apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: minecraft-proxy
  namespace: minecraft
spec:
  interval: 1h
  url: oci://ghcr.io/itzg/minecraft-server-charts/minecraft-proxy
  layerSelector:
    mediaType: 'application/vnd.cncf.helm.chart.content.v1.tar+gzip'
    operation: copy
  ref:
    semver: 'v3.9.0'