apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: minecraft-proxy
  namespace: minecraft
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: minecraft-proxy
    namespace: minecraft
  values:
    minecraftProxy:
      type: VELOCITY
      velocityVersion: 3.4.0
      onlineMode: true