---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mcdo-velocity-config
  namespace: minecraft
data:
  velocity.toml: |
    config-version = "2.7"
    bind = "0.0.0.0:25565"
    motd = "Cluster McDo Project"
    show-max-players = 45
    online-mode = true
    force-key-authentication = true
    prevent-client-proxy-connections = true
    player-info-forwarding-mode = "modern"
    forwarding-secret-file = "forwarding.secret"
    announce-forge = false
    kick-existing-players = false
    ping-passthrough = "disabled"
    sample-players-in-ping = false
    enable-player-address-logging = true

    [servers]
    advanced = "mcdo-advanced.minecraft.svc.cluster.local:25565"
    try = [
        "advanced"
    ]

    [forced-hosts]

    [advanced]
    compression-threshold = 256
    compression-level = -1
    login-ratelimit = 0
    connection-timeout = 5000
    read-timeout = 30000
    haproxy-protocol = false
    tcp-fast-open = true
    bungee-plugin-message-channel = true
    show-ping-requests = false
    failover-on-unexpected-server-disconnect = true
    announce-proxy-commands = false
    log-command-executions = true
    log-player-connections = true
    accepts-transfers = false
    enable-reuse-port = true
    command-rate-limit = 50
    forward-commands-if-rate-limited = true
    kick-after-rate-limited-commands = 0
    tab-complete-rate-limit = 10
    kick-after-rate-limited-tab-completes = 0

    [query]
    enabled = false
    port = 25565
    map = "Velocity"
    show-plugins = false
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mcdo-velocity
  namespace: minecraft
spec:
  interval: 1h
  timeout: 5m
  chart:
    spec:
      chart: minecraft-proxy
      version: 3.9.0
      sourceRef:
        kind: HelmRepository
        name: minecraft-server-charts
        namespace: minecraft
      interval: 5m
  releaseName: mcdo-velocity
  values:
    image:
      repository: itzg/mc-proxy
      tag: java25
    extraVolumes:
      - volumes:
          - name: velocity-config
            configMap:
              name: mcdo-velocity-config
        volumeMounts:
          - name: velocity-config
            mountPath: /server/velocity.toml
            subPath: velocity.toml
            readOnly: true
    minecraftProxy:
      type: VELOCITY
      velocityVersion: 3.4.0-SNAPSHOT
      velocityForwardingSecret: Wr8Uw0WIU26GmX
      velocityForwardingSecretFilePath: /server/forwarding.secret
    serviceAnnotations:
      "mc-router.itzg.me/externalServerName": "mcdo.polydo.dev"
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mcdo-advanced
  namespace: minecraft
spec:
  interval: 1h
  timeout: 5m
  chart:
    spec:
      chart: minecraft
      version: 5.0.0
      sourceRef:
        kind: HelmRepository
        name: minecraft-server-charts
        namespace: minecraft
      interval: 5m
  releaseName: mcdo-advanced
  values:
    image:
      tag: java25-graalvm
    fullnameOverride: mcdo-advanced
    resources:
      requests:
        memory: 8192Mi
        cpu: 2000m
    minecraftServer:
      eula: TRUE
      version: 1.21.10
      type: FABRIC
      fabricLauncherVersion: 1.1.0
      fabricLoaderVersion: 0.18.1
      difficulty: hard
      viewDistance: 12
      memory: 8192M
      modrinth:
        projects:
          - fabric:c2me-fabric:release
          - fabric:controlify:release
          - fabric:ferrite-core:release
          - fabric:lithium:release
          - fabric:modernfix-mvus:release
          - fabric:scalablelux:release
          - fabric:simple-voice-chat:release
          - fabric:sound-physics-remastered:pDo1ElL2
          - fabric:vmp-fabric:nCucW7Sl
          - fabric:xaeros-world-map:release
          - fabric:fabricproxy-lite:release
          - datapack:terralith:release
          - datapack:dungeons-and-taverns:release
          - datapack:dungeons-and-taverns-ancient-city-overhaul:release
          - datapack:dungeons-and-taverns-desert-temple-overhaul:release
          - datapack:dnt-enchant-disabler:release
          - datapack:dungeons-and-taverns-jungle-temple-overhaul:release
          - datapack:dungeons-and-taverns-nether-fortress-overhaul:release
          - datapack:dungeons-and-taverns-ocean-monument-overhaul:release
          - datapack:dungeons-and-taverns-pillager-outpost-overhaul:release
          - datapack:dungeons-and-taverns-stronghold-overhaul:release
          - datapack:dungeons-and-taverns-swamp-hut-overhaul:release
          - datapack:dungeons-and-taverns-woodland-mansion-overhaul:release
        downloadDependencies: required
